#Time limit
minutesAFK: 15

#Checks if a player is AFK every x seconds and stores the data
#More seconds -> Less accuracy less lag
#Fewer seconds -> More accuracy more lag
#Find a balance, start trying with fewer seconds
secondsInterval: 1